name: docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv (with caching)
        uses: astral-sh/setup-uv@v10.0.0
        with:
          python-version: "3.14"
          enable-cache: true
          ignore-nothing-to-cache: true
          cache-dependency-glob: uv.lock

      - name: Build HTML docs
        run: uv run --locked --extra docs sphinx-build -b html docs/source docs/_build/html

      - name: Build doctests
        run: uv run --locked --extra docs sphinx-build -b doctest docs/source docs/_build/doctest
